### ISSUE TITLE
Support json and jsonb types for postgres

### ISSUE THREAD

**Issue by rabbiveesh** [nrdvana/perl-DBIx-Class-ResultDDL#6]
What are your thoughts for adding a `json` or `jsonb` sugar type? That perhaps will auto-include `inflate_json`?

**Comment by nrdvana** [comment]
I did in 30c3c2a9f5fe31eaea8168c0b6b327bce8127e89 though I didn't document them yet.  I'm not sure if automatic inflate_json would be the best thing to do, though.  I have several places in my projects where I don't auto-decode the json columns so that I can avoid unneeded overhead (decode them on demand).  Ideally the DBIC plugin would decode them on demand, but I think the serializer code always runs immediately.  On the other hand, I have a lot of code where it would be convenient.

Now that you mention it, the other frequent deserialize I use is DateTime.  If I add ``inflate_datetime``, I would not add that as a default, because some people use different date classes (like Date::Tiny) or use the string direct form the DB because it's good enough for some applications.  So in that case, if ``datetime`` does not imply ``inflate_datetime`` then ``json`` probably shouldn't imply ``inflate_json``.

**Comment by rabbiveesh** [comment]
Oh, great.

I hear the argument not to inflate by default. Didn't realize you had added
the json type.

Looking forward to the release!

**Comment by nrdvana** [comment]
I added some changes to the latest 0.90_03 that you might like.  If you specify

    use DBIx::Class::ResultDDL qw/ -V1 -inflate_json /;

every json or jsonb column you declare will get ``inflate_json`` automatically.
