### ISSUE TITLE
Sugar to turn off DBIC's cascade

### ISSUE THREAD

**Issue by rabbiveesh** [nrdvana/perl-DBIx-Class-ResultDDL#9]
I just hit a bug in my app b/c DBIC cascades on the perl side by default, and I had forgotten to add `dbic_cascade(0)` to a certain rel, which was deleting things it shouldn't have.

Could we add an option simillar to `-inflate_json` that will default all relatinships to having dbic_cascade off?

**Comment by nrdvana** [comment]
The helpers with ‘rel_’ prefix do this by default.  The idea was that “might have” “has one” and “belongs to” are all describing an ownership, and dbic cascade is appropriate for ownership, but then I added generic non-ownership methods “rel_one” and “rel_many” which set dbic_cascade(0) automatically.

Does this pattern work for your use case?

**Comment by nrdvana** [comment]
As an example, in one of my apps I have a customer table with contacts, and contacts have a zip code in their address which related to a zip_code table.   I declare the first as a contact belongs_to the customer, because if a customer were deleted I would want to remove all the contacts as well.  I declare the zip code relation as customer rel_one to zip_code, because deleting the contact should not delete the zip code, and deleting the zip code (as sometimes happens during sync to a national database) should not delete the contacts.  In fact, the bug of deleting zip code records was what originally prompted me to write rel_one and rel_many which in turn sort of spawned the idea for this module :-)

**Comment by rabbiveesh** [comment]
You know, I read the docs for `rel_one` and co a few times, and this point didn't process. I'll close this ticket and think if I'd want to change the docs.
